import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Noise-Cancelling Headphones",
    description:
      "Experience premium sound quality with these wireless noise-cancelling headphones. Perfect for travel, work, or relaxation, these headphones deliver crisp highs and deep bass while blocking out ambient noise. With a comfortable over-ear design and long battery life, you can enjoy your music all day long.",
    price: 249.99,
    originalPrice: 299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    stock: 15,
    onSale: true,
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description:
      "Track your fitness goals with this advanced smart watch. Features include heart rate monitoring, step counting, sleep tracking, and workout analysis. The waterproof design makes it perfect for swimming and other water activities. Connect to your smartphone for notifications and music control.",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    rating: 4.2,
    reviews: 95,
    inStock: true,
    stock: 20,
    onSale: false,
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description:
      "Made from 100% organic cotton, this comfortable t-shirt is both stylish and environmentally friendly. The breathable fabric keeps you cool in warm weather, while the classic design pairs well with any outfit. Available in multiple colors and sizes.",
    price: 29.99,
    originalPrice: 39.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Clothing",
    rating: 4.0,
    reviews: 42,
    inStock: true,
    stock: 50,
    onSale: true,
  },
  {
    id: "4",
    name: "Professional Chef's Knife",
    description:
      "Elevate your cooking with this high-quality chef's knife. The sharp, stainless steel blade makes chopping, slicing, and dicing effortless. The ergonomic handle provides a comfortable grip for precise control. A must-have tool for any home cook or professional chef.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Kitchen",
    rating: 4.8,
    reviews: 76,
    inStock: true,
    stock: 30,
    onSale: false,
  },
  {
    id: "5",
    name: "Leather Crossbody Bag",
    description:
      "This stylish leather crossbody bag combines fashion and functionality. With multiple compartments for organization and an adjustable strap for comfort, it's perfect for everyday use. The premium leather construction ensures durability and a timeless look.",
    price: 129.99,
    originalPrice: 159.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
    rating: 4.3,
    reviews: 58,
    inStock: true,
    stock: 12,
    onSale: true,
  },
  {
    id: "6",
    name: "Portable Bluetooth Speaker",
    description:
      "Take your music anywhere with this compact Bluetooth speaker. Despite its small size, it delivers powerful, room-filling sound. The waterproof design makes it perfect for outdoor adventures, while the long battery life ensures the music keeps playing all day long.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    rating: 4.1,
    reviews: 112,
    inStock: true,
    stock: 25,
    onSale: false,
  },
  {
    id: "7",
    name: "Ceramic Plant Pot Set",
    description:
      "Add a touch of elegance to your home with this set of three ceramic plant pots. The minimalist design complements any decor style, while the drainage holes ensure your plants stay healthy. Perfect for indoor plants, herbs, or succulents.",
    price: 49.99,
    originalPrice: 59.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home",
    rating: 4.6,
    reviews: 37,
    inStock: true,
    stock: 18,
    onSale: true,
  },
  {
    id: "8",
    name: "Yoga Mat",
    description:
      "Enhance your yoga practice with this high-quality mat. The non-slip surface provides stability for all poses, while the cushioned material offers comfort for your joints. Lightweight and easy to carry with the included strap, it's perfect for yoga on the go.",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Fitness",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    stock: 40,
    onSale: false,
  },
]
